### ISSUE TITLE
Iterating ObservableGroup by index does not work properly

### ISSUE THREAD

**Issue by JayPavlina** [EcsRx/ecsrx#7] opened 2018-12-14 12:14 UTC
When doing:

`for (int i = 0; i < observableGroup.Count; i++) {
    var entity = observableGroup[i];
}`

The returned entity will sometimes be null.

**Comment by grofit** [comment] 2018-12-14 19:37
Thanks for raising this, the issue is down to the re-use of existing indexes inside the list which wasnt accounted for, luckily this is just in the prototype branch and not in the master releases. I will look into the avenues to trying to keep performance high but also removing the output of nulls.

**Comment by grofit** [comment] 2018-12-17 13:21
This should be fixed in the `Parallel` branch, I will mark this as fixed but feel free to re-raise if its causing issues.

**Closed as completed by grofit** 2018-12-17 13:21 UTC
Labels: bug, In Preview Versions
